"""create tables

Revision ID: e7f87e0a6be6
Revises:
Create Date: 2025-10-14 18:06:46.641782

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7f87e0a6be6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedbacks",
        sa.Column("username", sa.String(length=128), nullable=True),
        sa.Column("product_valuation", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wb_id", sa.String(length=64), nullable=False),
        sa.Column("nm_id", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("created_at_wb", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("loaded", "generated", "sent", "failed", name="status"),
            nullable=False,
        ),
        sa.Column("answer_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedbacks")),
        sa.UniqueConstraint("wb_id", name=op.f("uq_feedbacks_wb_id")),
    )
    op.create_index(
        op.f("ix_feedbacks_feedbacks_status"),
        "feedbacks",
        ["status"],
        unique=False,
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wb_id", sa.String(length=64), nullable=False),
        sa.Column("nm_id", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("created_at_wb", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("loaded", "generated", "sent", "failed", name="status"),
            nullable=False,
        ),
        sa.Column("answer_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questions")),
        sa.UniqueConstraint("wb_id", name=op.f("uq_questions_wb_id")),
    )
    op.create_index(
        op.f("ix_questions_questions_status"),
        "questions",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_questions_questions_status"), table_name="questions"
    )
    op.drop_table("questions")
    op.drop_index(
        op.f("ix_feedbacks_feedbacks_status"), table_name="feedbacks"
    )
    op.drop_table("feedbacks")
    # ### end Alembic commands ###
