"""create product_name collumn

Revision ID: 77de3974db44
Revises: e7f87e0a6be6
Create Date: 2025-10-20 16:35:20.564840

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "77de3974db44"
down_revision: Union[str, Sequence[str], None] = "e7f87e0a6be6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "feedbacks",
        sa.Column("product_name", sa.String(length=128), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("feedbacks", "product_name")
    # ### end Alembic commands ###
